const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('web/app.js','utf8');
const context=vm.createContext({state:{size:9,analyses:{}},move:4});
vm.runInContext('function atMove(){return move;}\n'+source.slice(source.indexOf('function territoryAnalysis()'),source.indexOf('function renderBoard()')),context);
const estimate=(moveNumber,turn='W')=>({moveNumber,turn,ownership:Array(81).fill(.8)});
const read=()=>vm.runInContext('territoryAnalysis()',context);
context.state.analyses={3:estimate(3)};
assert.equal(read().moveNumber,3,'retain ownership after the AI moves');
assert.equal(read().turn,'W','retain the estimate perspective across turn changes');
context.state.analysis=estimate(4,'B');
assert.equal(read().moveNumber,4,'replace with current estimate');
context.move=2;
assert.equal(read().ownership,undefined,'never show future ownership during review');
context.move=4;context.state={size:9,analyses:{}};
assert.equal(read().ownership,undefined,'new games do not reuse old ownership');
context.state.analyses={4:{...estimate(4),ownership:[.8]}};
assert.equal(read().ownership,undefined,'reject a different board size');
console.log('Territory overlay regression checks passed.');
